platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotaldata/gpdb6-centos7-test
inputs:
  - name: gpdb_main_src
  - name: explain_output
  - name: explain_output_baseline
outputs:
  - name: diffs
params:
  prefix:
run:
  path: gpdb_main_src/concourse/scripts/diff_explain_results_with_baseline.bash

