platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotaldata/gpdb6-centos7-test
inputs:
  - name: bin_gpdb
  - name: gpdb_src
  - name: gp_workloads
  - name: gporca-commits-to-test
params:
  MODE:
  ACTION:
  CONFIGURE_OPTION:
  WORKLOAD:
  GUCS:
run:
  path: sh
  args:
  - -exc
  - |
    cp -r gp_workloads/${WORKLOAD}/sql sql
    cp gp_workloads/${WORKLOAD}/schema_6X.sql schema.sql
    cp gp_workloads/${WORKLOAD}/stats_6X.sql schema.sql

    gpdb_src/concourse/scripts/build_gpdb.py ${MODE} ${ACTION} ${CONFIGURE_OPTION}
    #  - |
    #    readarray -d ';' -t workloads_to_run <<< `cat workload.txt`
    #    for $i in "${workloads_to_run[@]}"
    #    do
    #      if [[ $i == "all" || $i == ${WORKLOAD} ]]
    #      then
    #        gpdb_src/concourse/scripts/build_gpdb.py ${MODE} ${ACTION} ${CONFIGURE_OPTION}
    #        break
    #      fi
    #    done
