platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotaldata/gpdb6-centos7-test
inputs:
  - name: bin_gpdb
  - name: gpdb_src
params:
  MODE:
  ACTION:
  CONFIGURE_OPTION:
run:
  path: sh
  args:
  - -exc
  - |
    gpdb_src/concourse/scripts/build_gpdb.py ${MODE} ${ACTION} ${CONFIGURE_OPTION}
