## ======================================================================
## resources
## ======================================================================

resources:
- name: gpdb_src
  type: git
  source:
    branch: {{gpdb-git-branch}}
    private_key: {{gpdb-git-key}}
    uri: {{gpdb-git-remote}}

- name: centos511-java7-gpdb-dev-image
  type: docker-image
  source:
    repository: pivotaldata/centos511-java7-gpdb-dev-image
    username: {{docker_username}}
    password: {{docker_password}}

- name: bin_gpdb_centos
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: bin_gpdb_centos/bin_gpdb.tar.gz

- name: sync_tools_gpdb_centos
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: sync_tools_gpdb_centos/sync_tools_gpdb.tar.gz

- name: installer_rhel5_gpdb_rc
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: deliverables/greenplum-db-4.3.9.1-build-1-rhel5-x86_64.zip

- name: installer_rhel5_gpdb_clients
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: deliverables/greenplum-clients-4.3.9.1-build-1-rhel5-x86_64.zip

- name: installer_appliance_rhel5_gpdb_rc
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: deliverables/greenplum-db-appliance-4.3.9.1-build-1-rhel5-x86_64.zip

- name: installer_rhel5_gpdb_connectivity
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: deliverables/greenplum-connectivity-4.3.9.1-build-1-rhel5-x86_64.zip

- name: installer_rhel5_gpdb_loaders
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: deliverables/greenplum-loaders-4.3.9.1-build-1-rhel5-x86_64.zip

- name: postgis_rhel5_gppkg
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: deliverables/postgis-ossv2.0.3_pv2.0.1_gpdb4.3orca-rhel5-x86_64.gppkg

- name: ddboost_rhel5_gppkg
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: deliverables/ddboostlib-2.6.2_pv1.2.1_gpdb4.3orca-rhel5-x86_64.gppkg

- name: pgcrypto_rhel5_gppkg
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: deliverables/pgcrypto-ossv1.1_pv1.2_gpdb4.3orca-rhel5-x86_64.gppkg

- name: plperl_rhel5_gppkg
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: deliverables/plperl-ossv5.12.4_pv1.3_gpdb4.3orca-rhel5-x86_64.gppkg

- name: pljava_rhel5_gppkg
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: deliverables/pljava-ossv1.4.0_pv1.3_gpdb4.3orca-rhel5-x86_64.gppkg

- name: plr_rhel5_gppkg
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: deliverables/plr-ossv8.3.0.15_pv2.1_gpdb4.3orca-rhel5-x86_64.gppkg

## ======================================================================
## jobs
## ======================================================================

# Stage 1: Build and C Unit Tests

jobs:
- name: compile_gpdb_centos
  public: true
  plan:
  - aggregate:
    - get: gpdb_src
      trigger: true
    - get: centos511-java7-gpdb-dev-image
  - task: compile_gpdb
    file: gpdb_src/ci/concourse/compile_gpdb.yml
    image: centos511-java7-gpdb-dev-image
    params:
      TARGET_OS: centos
      BLD_TARGETS: clients connectivity loaders
  - aggregate:
    - put: bin_gpdb_centos
      params:
        file: gpdb_artifacts/bin_gpdb.tar.gz
    - put: installer_rhel5_gpdb_clients
      params:
        file: gpdb_artifacts/greenplum-clients-*-RHEL5-x86_64.zip
    - put: installer_rhel5_gpdb_connectivity
      params:
        file: gpdb_artifacts/greenplum-connectivity-*-RHEL5-x86_64.zip
    - put: installer_rhel5_gpdb_loaders
      params:
        file: gpdb_artifacts/greenplum-loaders-*-RHEL5-x86_64.zip
    - put: postgis_rhel5_gppkg
      params:
        file: gpdb_artifacts/postgis-ossv2.0.3_pv2.0.1_gpdb4.3orca-rhel5-x86_64.gppkg
    - put: pgcrypto_rhel5_gppkg
      params:
        file: gpdb_artifacts/pgcrypto-ossv1.1_pv1.2_gpdb4.3orca-rhel5-x86_64.gppkg
    - put: ddboost_rhel5_gppkg
      params:
        file: gpdb_artifacts/ddboostlib-2.6.2_pv1.2.1_gpdb4.3orca-rhel5-x86_64.gppkg
    - put: pljava_rhel5_gppkg
      params:
        file: gpdb_artifacts/pljava-ossv1.4.0_pv1.3_gpdb4.3orca-rhel5-x86_64.gppkg
    - put: plperl_rhel5_gppkg
      params:
        file: gpdb_artifacts/plperl-ossv5.12.4_pv1.3_gpdb4.3orca-rhel5-x86_64.gppkg
    - put: plr_rhel5_gppkg
      params:
        file: gpdb_artifacts/plr-ossv8.3.0.15_pv2.1_gpdb4.3orca-rhel5-x86_64.gppkg
    - put: sync_tools_gpdb_centos
      params:
        file: sync_tools_gpdb/sync_tools_gpdb.tar.gz

# Stage 2: Installcheck and Python Unit Tests

# If a new test is added to this stage, add the name of the job to the list of
# stage 2 jobs under the following line in the first job in the stage 3 section:
#
#     passed: &Stage2JobsCentos

- name: icb_orca_centos
  public: true
  plan:
  - aggregate:
    - get: gpdb_src
      passed: [compile_gpdb_centos]
    - get: sync_tools_gpdb
      resource: sync_tools_gpdb_centos
      passed: [compile_gpdb_centos]
    - get: bin_gpdb
      resource: bin_gpdb_centos
      passed: [compile_gpdb_centos]
      trigger: true
  - task: ic_gpdb
    file: gpdb_src/ci/concourse/ic_gpdb.yml
    params:
      MAKE_TEST_COMMAND: installcheck-bugbuster
      BLDWRAP_POSTGRES_CONF_ADDONS: optimizer=on
      TEST_OS: centos

- name: icb_planner_centos
  public: true
  plan:
  - aggregate:
    - get: gpdb_src
      passed: [compile_gpdb_centos]
    - get: sync_tools_gpdb
      resource: sync_tools_gpdb_centos
      passed: [compile_gpdb_centos]
    - get: bin_gpdb
      resource: bin_gpdb_centos
      passed: [compile_gpdb_centos]
      trigger: true
  - task: ic_gpdb
    file: gpdb_src/ci/concourse/ic_gpdb.yml
    params:
      MAKE_TEST_COMMAND: installcheck-bugbuster
      BLDWRAP_POSTGRES_CONF_ADDONS: ""
      TEST_OS: centos

- name: icg_orca_centos
  public: true
  plan:
  - aggregate:
    - get: gpdb_src
      passed: [compile_gpdb_centos]
    - get: sync_tools_gpdb
      resource: sync_tools_gpdb_centos
      passed: [compile_gpdb_centos]
    - get: bin_gpdb
      resource: bin_gpdb_centos
      passed: [compile_gpdb_centos]
      trigger: true
  - task: ic_gpdb
    file: gpdb_src/ci/concourse/ic_gpdb.yml
    params:
      MAKE_TEST_COMMAND: installcheck-good
      BLDWRAP_POSTGRES_CONF_ADDONS: optimizer=on
      TEST_OS: centos

- name: icg_planner_centos
  public: true
  plan:
  - aggregate:
    - get: gpdb_src
      passed: [compile_gpdb_centos]
    - get: sync_tools_gpdb
      resource: sync_tools_gpdb_centos
      passed: [compile_gpdb_centos]
    - get: bin_gpdb
      resource: bin_gpdb_centos
      passed: [compile_gpdb_centos]
      trigger: true
  - task: ic_gpdb
    file: gpdb_src/ci/concourse/ic_gpdb.yml
    params:
      MAKE_TEST_COMMAND: installcheck-good
      BLDWRAP_POSTGRES_CONF_ADDONS: ""
      TEST_OS: centos

# Stage 3a: Packaging the Release Candidate (rc)

- name: gpdb_rc_packaging_centos
  public: true
  plan:
  - aggregate:
    - get: gpdb_src
      passed: [icg_planner_centos]
    - get: bin_gpdb
      resource: bin_gpdb_centos
      passed:
        - icb_orca_centos
        - icb_planner_centos
        - icg_orca_centos
        - icg_planner_centos
      trigger: true
  - task: remove_files_for_rc
    file: gpdb_src/ci/concourse/remove_files_for_rc.yml
  - aggregate:
    - task: gpdb_rc_packaging_centos
      file: gpdb_src/ci/concourse/gpdb_packaging.yml
      input_mapping:
        bin_gpdb: rc_bin_gpdb
      output_mapping:
        packaged_gpdb: packaged_gpdb_rc
      params:
        INSTALL_SCRIPT_SRC: gpdb_src/gpAux/releng/bin/installer-header-rhel5-gpdb.sh
        INSTALLER_ZIP: packaged_gpdb/greenplum-db-4.3.9.1-build-1-rhel5-x86_64.zip
        ADD_README_INSTALL: true
    - task: gpdb_appliance_rhel5_rc_packaging
      file: gpdb_src/ci/concourse/gpdb_packaging.yml
      input_mapping:
        bin_gpdb: rc_bin_gpdb
      output_mapping:
        packaged_gpdb: packaged_gpdb_appliance_rc
      params:
        INSTALL_SCRIPT_SRC: gpdb_src/gpAux/releng/bin/installer-appliance-header-rhel5-gpdb.sh
        INSTALLER_ZIP: packaged_gpdb/greenplum-db-appliance-4.3.9.1-build-1-rhel5-x86_64.zip
  - aggregate:
    - put: installer_rhel5_gpdb_rc
      params:
        file: packaged_gpdb_rc/greenplum-db-4.3.9.1-build-1-rhel5-x86_64.zip
    - put: installer_appliance_rhel5_gpdb_rc
      params:
        file: packaged_gpdb_appliance_rc/greenplum-db-appliance-4.3.9.1-build-1-rhel5-x86_64.zip

# Stage 3b: Packaging of source code
- name: apply_morgan_stanley_specific_patches
  public: true
  plan:
  - aggregate:
    - get: gpdb_src
      passed: [gpdb_rc_packaging_centos]
    - get: installer_rhel5_gpdb_rc
      passed: [gpdb_rc_packaging_centos]
    - get: installer_rhel5_gpdb_clients
      passed: [compile_gpdb_centos]
    - get: installer_rhel5_gpdb_connectivity
      passed: [compile_gpdb_centos]
    - get: installer_rhel5_gpdb_loaders
      passed: [compile_gpdb_centos]
    - get: pgcrypto_rhel5_gppkg
      passed: [compile_gpdb_centos]
    - get: plr_rhel5_gppkg
      passed: [compile_gpdb_centos]
    - get: pljava_rhel5_gppkg
      passed: [compile_gpdb_centos]
  - task: update_artifacts
    file: gpdb_src/ci/concourse/apply_morgan_stanley_patches.yml

# Stage 3c: Sync packages to dist.eng.pivotal.io
# - name: gpdb_sync_to_dist
#   public: true
#   serial: true
#   plan:
#   - aggregate:
#     - get: gpdb_src
#     - get: gpdb_src_archive
#       passed: [gpdb_src_packaging]
#       trigger: true
#     - get: installer_rhel5_gpdb
#       passed: [gpdb_packaging_centos]
#     - get: installer_appliance_rhel5_gpdb
#       passed: [gpdb_packaging_centos]
#       trigger: true
#     - get: installer_rhel5_gpdb_clients
#       passed: [compile_gpdb_centos]
#     - get: installer_rhel5_gpdb_connectivity
#       passed: [compile_gpdb_centos]
#     - get: installer_rhel5_gpdb_loaders
#       passed: [compile_gpdb_centos]
#     - get: postgis_rhel5_gppkg
#       passed: [compile_gpdb_centos]
#     - get: plr_rhel5_gppkg
#       passed: [compile_gpdb_centos]
#     - get: pljava_rhel5_gppkg
#       passed: [compile_gpdb_centos]
#     - get: plperl_rhel5_gppkg
#       passed: [compile_gpdb_centos]
#     - get: ddboost_rhel5_gppkg
#       passed: [compile_gpdb_centos]
#     - get: pgcrypto_rhel5_gppkg
#       passed: [compile_gpdb_centos]
#   - aggregate:
#     - task: gpdb_src_sync_to_dist
#       file: gpdb_src/ci/concourse/gpdb_sync_to_dist.yml
#       input_mapping:
#         artifact_to_upload: gpdb_src_archive
#       params:
#         FILE_TO_UPLOAD: artifact_to_upload/greenplum-db-4.3.9.1-src.tar.gz
#         BUCKET_NAME: {{bucket-name}}
#         SSH_KEY: {{dist-ssh-key}}
#     - task: gpdb_rhel5_sync_to_dist
#       file: gpdb_src/ci/concourse/gpdb_sync_to_dist.yml
#       input_mapping:
#         artifact_to_upload: installer_rhel5_gpdb
#       params:
#         FILE_TO_UPLOAD: artifact_to_upload/greenplum-db-4.3.9.1-rhel5-x86_64.zip
#         BUCKET_NAME: {{bucket-name}}
#         SSH_KEY: {{dist-ssh-key}}
#     - task: gpdb_rhel5_appliance_sync_to_dist
#       file: gpdb_src/ci/concourse/gpdb_sync_to_dist.yml
#       input_mapping:
#         artifact_to_upload: installer_appliance_rhel5_gpdb
#       params:
#         FILE_TO_UPLOAD: artifact_to_upload/greenplum-db-appliance-4.3.9.1-rhel5-x86_64.zip
#         BUCKET_NAME: {{bucket-name}}
#         SSH_KEY: {{dist-ssh-key}}
#     - task: gpdb_rhel5_clients_sync_to_dist
#       file: gpdb_src/ci/concourse/gpdb_sync_to_dist.yml
#       input_mapping:
#         artifact_to_upload: installer_rhel5_gpdb_clients
#       params:
#         FILE_TO_UPLOAD: artifact_to_upload/greenplum-clients-4.3.9.1-build-1-rhel5-x86_64.zip
#         BUCKET_NAME: {{bucket-name}}
#         SSH_KEY: {{dist-ssh-key}}
#     - task: gpdb_rhel5_connectivity_sync_to_dist
#       file: gpdb_src/ci/concourse/gpdb_sync_to_dist.yml
#       input_mapping:
#         artifact_to_upload: installer_rhel5_gpdb_connectivity
#       params:
#         FILE_TO_UPLOAD: artifact_to_upload/greenplum-connectivity-4.3.9.1-build-1-rhel5-x86_64.zip
#         BUCKET_NAME: {{bucket-name}}
#         SSH_KEY: {{dist-ssh-key}}
#     - task: gpdb_rhel5_loaders_sync_to_dist
#       file: gpdb_src/ci/concourse/gpdb_sync_to_dist.yml
#       input_mapping:
#         artifact_to_upload: installer_rhel5_gpdb_loaders
#       params:
#         FILE_TO_UPLOAD: artifact_to_upload/greenplum-loaders-4.3.9.1-build-1-rhel5-x86_64.zip
#         BUCKET_NAME: {{bucket-name}}
#         SSH_KEY: {{dist-ssh-key}}
#     - task: postgis_rhel5_gppkg_sync_to_dist
#       file: gpdb_src/ci/concourse/gpdb_sync_to_dist.yml
#       input_mapping:
#         artifact_to_upload: postgis_rhel5_gppkg
#       params:
#         FILE_TO_UPLOAD: artifact_to_upload/postgis-ossv2.0.3_pv2.0.1_gpdb4.3orca-rhel5-x86_64.gppkg
#         BUCKET_NAME: {{bucket-name}}
#         SSH_KEY: {{dist-ssh-key}}
#     - task: pljava_rhel5_gppkg_sync_to_dist
#       file: gpdb_src/ci/concourse/gpdb_sync_to_dist.yml
#       input_mapping:
#         artifact_to_upload: pljava_rhel5_gppkg
#       params:
#         FILE_TO_UPLOAD: artifact_to_upload/pljava-ossv1.4.0_pv1.3_gpdb4.3orca-rhel5-x86_64.gppkg
#         BUCKET_NAME: {{bucket-name}}
#         SSH_KEY: {{dist-ssh-key}}
#     - task: plperl_rhel5_gppkg_sync_to_dist
#       file: gpdb_src/ci/concourse/gpdb_sync_to_dist.yml
#       input_mapping:
#         artifact_to_upload: plperl_rhel5_gppkg
#       params:
#         FILE_TO_UPLOAD: artifact_to_upload/plperl-ossv5.12.4_pv1.3_gpdb4.3orca-rhel5-x86_64.gppkg
#         BUCKET_NAME: {{bucket-name}}
#         SSH_KEY: {{dist-ssh-key}}
#     - task: ddboost_rhel5_gppkg_sync_to_dist
#       file: gpdb_src/ci/concourse/gpdb_sync_to_dist.yml
#       input_mapping:
#         artifact_to_upload: ddboost_rhel5_gppkg
#       params:
#         FILE_TO_UPLOAD: artifact_to_upload/ddboostlib-2.6.2_pv1.2.1_gpdb4.3orca-rhel5-x86_64.gppkg
#         BUCKET_NAME: {{bucket-name}}
#         SSH_KEY: {{dist-ssh-key}}
#     - task: plr_rhel5_gppkg_sync_to_dist
#       file: gpdb_src/ci/concourse/gpdb_sync_to_dist.yml
#       input_mapping:
#         artifact_to_upload: plr_rhel5_gppkg
#       params:
#         FILE_TO_UPLOAD: artifact_to_upload/plr-ossv8.3.0.15_pv2.1_gpdb4.3orca-rhel5-x86_64.gppkg
#         BUCKET_NAME: {{bucket-name}}
#         SSH_KEY: {{dist-ssh-key}}
#     - task: pgcrypto_rhel5_gppkg_sync_to_dist
#       file: gpdb_src/ci/concourse/gpdb_sync_to_dist.yml
#       input_mapping:
#         artifact_to_upload: pgcrypto_rhel5_gppkg
#       params:
#         FILE_TO_UPLOAD: artifact_to_upload/pgcrypto-ossv1.1_pv1.2_gpdb4.3orca-rhel5-x86_64.gppkg
#         BUCKET_NAME: {{bucket-name}}
#         SSH_KEY: {{dist-ssh-key}}
